### ISSUE TITLE
Wordpress in sub-directory not working without defining WP_HOME, WP_SITEURL

### ISSUE THREAD

**Issue by wlanni** [studio24/wordpress-multi-env-config#11]
Hello,

I had some trouble getting wordpress to work in a subdirectory. Our company blog sits in a subdirectory /blog/. Database and everything is set, all worked fine until I installed this multi-env-config. 

To fix I had to add `. 'blog'` to the end of the Define WordPress Site URLs in the wp-config.php

`
if (!defined('WP_SITEURL')) {
    define('WP_SITEURL', $protocol . rtrim($hostname, '/') . '/blog');
}
if (!defined('WP_HOME')) {
    define('WP_HOME', $protocol . rtrim($hostname, '/') . '/blog');
}
`
Was this expected behavior?

**Comment by Kescay** [comment]
Had the same problem. What worked in my case was removing those lines entirely.

**Comment by richcaputo** [comment]
Same issue here, I need to define my SITEURL and HOME, but it breaks the site. Is there a work around for this?

**Comment by wlanni** [comment]
Rich, there are two suggestions in the thread: adding the sub directory to the end or removing completely. 

I've tried both, removing completely worked for me.

**Comment by simonrjones** [comment]
I am adding this as a feature for v2.0, which is currently being tested

**Comment by simonrjones** [comment]
This should be fixed in the current version which supports paths, e.g.

``
    'production'  => [
        'domain' => 'domain.com',
        'path'   => 'blog',
        'ssl'    => true,
    ],
``
