### ISSUE TITLE
Force SSL

### ISSUE THREAD

**Issue by ruelluna** [studio24/wordpress-multi-env-config#12]
how to force SSL using this?

**Comment by simonrjones** [comment]
I am adding this as a feature for v2.0, which is currently being tested

**Comment by ruelluna** [comment]
Gee! Thanks! Looking forward for this.

**Comment by newtlabs** [comment]
@ruelluna Why force SSL? That should be done with redirects at the server level...

**Comment by simonrjones** [comment]
Closing, since very old and I seem to have forgotten to close this off.  

Force SSL is now an option, set ssl to true in the wp-config.env.php file:

`'ssl'    => true`
