### ISSUE TITLE
How about setting diffrent db prefixes based on env aswell?

### ISSUE THREAD

**Issue by chrillep** [studio24/wordpress-multi-env-config#13]
[Installing Multiple Blogs](https://codex.wordpress.org/Installing_Multiple_Blogs)

good for using same codebase on diffrent domains

heres a sample that updates db prefix, needs some updates in wp config default to change the prefix to

```
$table_prefix  = 'wp_'.$country_prefix;


// Doesnt work with co.uk
function get_tld( $hostname ) {
    $tld = strrchr ( $hostname, "." );
    $tld = substr ( $tld, 1 );
    return $tld;
}

$country_prefix = '';
switch ( $hostname ) {

    case strpos($hostname,'domain.dev') !== false:
    define('WP_ENV', 'development');
    define('DOMAIN_CURRENT_SITE', 'domain.dev');
    break;

    case strpos($hostname,'domain.TLD') !== false:
    define('WP_ENV', 'staging');
    define('DOMAIN_CURRENT_SITE', 'domain.TLD');
    define('DB_NAME', 'DB');
    break;

    case strpos($hostname,'domain') !== false:
    $tld = get_tld( $hostname );
    define('WP_ENV', 'staging');
    define('DOMAIN_CURRENT_SITE', 'www.domain.' . $tld);
    define('DB_NAME', 'DB');
    $country_prefix = $tld . '_';
    break;

    case strpos($hostname,'domain.TLD') !== false:
    default: 
    define('WP_ENV', 'production');
    define('DOMAIN_CURRENT_SITE', 'www.domain.TLD');
}
```

**Comment by chrillep** [comment]
`<?php

// Doesnt work with co.uk
function get_tld( $hostname ) {
    $tld = strrchr ( $hostname, "." );
    $tld = substr ( $tld, 1 );
    return $tld;
}

$country_prefix = '';
switch ( $hostname ) {

    case strpos($hostname,'domain.dev') !== false:
    define('WP_ENV', 'development');
    define('DOMAIN_CURRENT_SITE', 'domain.dev');
    break;

    case strpos($hostname,'domain.TLD') !== false:
    define('WP_ENV', 'staging');
    define('DOMAIN_CURRENT_SITE', 'domain.TLD');
    define('DB_NAME', 'DB');
    break;

    case strpos($hostname,'domain') !== false:
    $tld = get_tld( $hostname );
    define('WP_ENV', 'staging');
    define('DOMAIN_CURRENT_SITE', 'www.domain.' . $tld);
    define('DB_NAME', 'DB');
    $country_prefix = $tld . '_';
    break;

    case strpos($hostname,'domain.TLD') !== false:
    default: 
    define('WP_ENV', 'production');
    define('DOMAIN_CURRENT_SITE', 'www.domain.TLD');
}

?>`

**Comment by chrillep** [comment]
Also would be interesting if using same db with different prefixes to use the same usertables.

## Multiple Databases, Same Users
You can use the same userbase with all your blogs on the same domain, by defining the CUSTOM_USER_TABLE and optionally the CUSTOM_USER_META_TABLE constants to point to the same wp_your_blog_users and wp_your_blog_usermeta tables. See Editing wp-config.php/Custom User and Usermeta Tables.

[Custom User and Usermeta Tables](https://codex.wordpress.org/Editing_wp-config.php#Custom_User_and_Usermeta_Tables)

**Comment by chrillep** [comment]
the thing im trying to do is have multiple multisites in one db with country prefixes.

**Comment by simonrjones** [comment]
This is very old, so closing. 

You can set a custom table prefix via the $table_prefix variable, which you can do via this multi config tool or just with some custom code.
