### ISSUE TITLE
Ignore plugins based on env

### ISSUE THREAD

**Issue by panosru** [studio24/wordpress-multi-env-config#14]
Would cool to ignore some plugins based on env.

For instance in development env I don't need jetpack or pixelyourside etc but I need them in production

**Comment by SimonMayerhofer** [comment]
In my opinion this is something you should manage with a dependency manager like composer. It's great for doing what you want to do.

**Comment by simonrjones** [comment]
closing since not part of the functionality of this tool, as nice an idea as it is
