### ISSUE TITLE
URLs need updating

### ISSUE THREAD

**Issue by mkormendy** [studio24/wordpress-multi-env-config#17]
How is it that the urls don't need updating in the database?

**Comment by simonrjones** [comment]
This plugin sets the WP_SITEURL dynamically based on the environment so it is no longer necessary to set this in the DB (the config PHP file overrides any entry in the DB). 

If you've added content to a test site under a different URL that's a different issue and you may well have links to other pages which contain the test URL. For this we have a CLI script we run to search & replace for such links. See https://github.com/studio24/fix-staging-urls

**Comment by mkormendy** [comment]
I was referring to what you speak of in your second paragraph.
