### ISSUE TITLE
Using XAMPP localhost

### ISSUE THREAD

**Issue by gabyferman** [studio24/wordpress-multi-env-config#27]
Hi, I'm trying to use the dev version of my site on localhost, with `http://domain.local` but I'm not sure how to connect it. The production version: `http://domain.com` and staging version: `http://staging.domain.com`  share wp-admin, wp-includes and plugin folders, while the DBs and wp-content folders are different for each version.

For my local install I'm working on XAMPP and I would like to share the plugins and media folders for the three versions, though I don't know if what I need to configure for the development version, a.k.a. domain.local, is the wp-config.development.php or the wp-config.php in localhost?

**Comment by simonrjones** [comment]
If you're using this multi-environment config, then I think you should set domain.local as the development domain in wp-config.env.php:

``
$env = [
    ...
    'development' => [
        'domain' => 'domain.local',
        'path'   => '',
        'ssl'    => false,
    ],
];
``

Any custom settings for local environment can then be saved in: wp-config.development.php
