### ISSUE TITLE
SITE_URL and HOME are overridden

### ISSUE THREAD

**Issue by plingvorm** [studio24/wordpress-multi-env-config#33]
I have the set up in /core
So I put it in the env file.

But I do NOT want the url to show up including /core to customers.

Adding it to the environment file(s) does not work.

**Comment by missyjo3369** [comment]
Good deal help me 
![Screenshot_20210712-170918](https://user-images.githubusercontent.com/94876437/142955108-541f1d51-3807-4c65-93ba-15967f77487d.png)
![Screenshot_20211026-181714](https://user-images.githubusercontent.com/94876437/142955121-49b7de75-bbd9-43d2-b8c2-5bb1b6b1b0a9.png)
![Screenshot_20210712-170227](https://user-images.githubusercontent.com/94876437/142955141-49e8bfe3-cdb1-44f7-869b-28e6737ff2db.png)
![Screenshot_20210712-170220](https://user-images.githubusercontent.com/94876437/142955162-003b426a-3078-4119-a160-1dd06c9464e2.png)
![Screenshot_20210712-170201](https://user-images.githubusercontent.com/94876437/142955182-3ff7152b-8b2b-4203-8fa2-2c73d2175a7a.png)
![Screenshot_20210712-170152](https://user-images.githubusercontent.com/94876437/142955206-1fc1c58e-b145-4917-be5f-6c2d507e7612.png)
![Screenshot_20210712-170140](https://user-images.githubusercontent.com/94876437/142955234-11a79d91-54f4-4bcd-8037-51546ebb6d4f.png)

- [](url)

**Comment by missyjo3369** [comment]
Write back patten

**Comment by simonrjones** [comment]
Doing some tidying up on this repo, sorry for not replying a long time ago. 

I don't think this issue is related to the config system, it sounds like you've installed WP in a sub-folder which then displays to users. You need to install WordPress in your document root to avoid sub-folders appearing in the URL.
