### ISSUE TITLE
can you use 'localhost' as the domain hostname?

### ISSUE THREAD

**Issue by armyofda12mnkeys** [studio24/wordpress-multi-env-config#6]
Quick question... Can you use 'localhost' for the $hostname check, or you must setup vhosts/hosts file setup where there is a name like 'mywebsite.localhost' like your example.
Would be convenient to cover developers that don't setup a specific vhost for the Wordpress install/app.

**Comment by simonrjones** [comment]
yes, it is fine to use localhost. 

I've added some clarity to the docs in the wp-config.env.php file, see https://github.com/studio24/wordpress-multi-env-config/commit/c0c539f6b061c3fc5391f5a7ab58a9bd18400c6e
