### ISSUE TITLE
wp cli database error

### ISSUE THREAD

**Issue by filipvanreeth** [studio24/wordpress-multi-env-config#8]
When I use ex. wp plugin list with wp-cli I get this error:

Error:
<h1>Error establishing a database connection</h1>
<p>This either means that the username and password information in your <code>wp-config.php</code> file is incorrect or we can't contact the database server at <code></code>. This could mean your host's database server is down.</p>
<ul>
	<li>Are you sure you have the correct username and password?</li>
	<li>Are you sure that you have typed the correct hostname?</li>
	<li>Are you sure that the database server is running?</li>
</ul>
<p>If you're unsure what these terms mean you should probably contact your host. If you still need help you can always visit the <a href='https://wordpress.org/support/'>WordPress Support Forums</a>.</p>

Any idea how to fix this?

**Comment by simonrjones** [comment]
Sorry I've not replied earlier to this. 

You need to pass the environment to the wp-cli command to ensure the correct config file is loaded. This can be done as so:

wp help --env=development  

See the README for more
https://github.com/studio24/wordpress-multi-env-config/blob/master/README.md

If it still isn't working for you after you add the --env option please let me know.

**Comment by filipvanreeth** [comment]
Hi Simon,

Thanks.

Kind regards,
Filip

**Comment by simonrjones** [comment]
Marking as closed, let me know if you have any further issues
